---
- name: Set up development environment
  hosts: localhost
  vars:
    source_key: "./.ssh/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
  tasks:
    - include_tasks: tasks/ssh.yml
    - include_tasks: tasks/thefuck.yml
    # - include_tasks: tasks/chrome.yml
    # - include_tasks: tasks/git.yml
    # - include_tasks: tasks/node.yml
    - include_tasks: tasks/nvim.yml
    - include_tasks: tasks/terminal.yml
    # - include_tasks: tasks/phantom.yml
    # - include_tasks: tasks/docker.yml
    # - include_tasks: tasks/zsh.yml
    # - include_tasks: tasks/yabai.yml
