- name: Install NVM
  homebrew:
    name: nvm
    state: present
  tags: nvm

- name: Add NVM configuration to shell
  lineinfile:
    dest: ~/.zshrc
    line: 'export NVM_DIR="$HOME/.nvm" && . "/opt/homebrew/opt/nvm/nvm.sh"'
    create: yes
  tags: nvm

- name: Install Node.js (latest version via NVM)
  shell: |
    source ~/.zshrc
    nvm install node
  tags: node