- name: Install Zsh
  homebrew:
    name: zsh
    state: present
  tags: zsh

- name: Install Oh My Zsh
  shell: |
    sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  args:
    creates: ~/.oh-my-zsh
  tags: oh_my_zsh

- name: Set Zsh as default shell
  shell: chsh -s /bin/zsh
  tags: zsh